# Generated by Django 3.0.2 on 2020-02-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('1', 'Adventure'), ('2', 'Action'), ('3', 'Puzzle'), ('4', 'Strategy'), ('5', 'Other')], default=5, max_length=1),
        ),
    ]
