# Generated by Django 3.0.2 on 2020-02-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0002_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Action', 'Action'), ('Puzzle', 'Puzzle'), ('Strategy', 'Strategy'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
