# Generated by Django 3.0.2 on 2020-02-01 22:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0003_auto_20200127_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='checksum',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
