# Generated by Django 3.0.2 on 2020-02-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0004_purchase_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='checksum',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
