# Generated by Django 3.0.2 on 2020-02-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0007_auto_20200202_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
