# Generated by Django 3.0.2 on 2020-02-01 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0008_purchase_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='pid',
            field=models.UUIDField(default=uuid.UUID('55b1be74-4549-11ea-93d8-8c859056cc8e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
