# Generated by Django 3.0.2 on 2020-02-01 23:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0009_auto_20200202_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pid',
            field=models.UUIDField(default=uuid.UUID('7314649e-4549-11ea-9baa-8c859056cc8e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
