# Generated by Django 3.0.2 on 2020-02-01 23:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0010_auto_20200202_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pid',
            field=models.UUIDField(default=uuid.UUID('4eb9f01a-ea7f-4822-be60-e9e2e23654eb'), primary_key=True, serialize=False, unique=True),
        ),
    ]
