# Generated by Django 3.0.2 on 2020-02-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0012_auto_20200202_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='pid',
            field=models.UUIDField(default=9999, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
