# Generated by Django 3.0.2 on 2020-02-02 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0013_auto_20200202_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='checksum',
        ),
    ]
